/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.paraita.examples;

import picocli.CommandLine;

public class App {

    public static void main(String[] args) {

        int returnCode = new CommandLine(new CLIParser()).execute(args);
        System.exit(returnCode);

    }
}
